---
title: Network Canvas Documentation
timezone: UTC
baseurl: ''
email: info@networkcanvas.com
description: Documentation and information about the Network Canvas project. Network Canvas is free suite of tools that facilitate cutting edge personal networks research.
logo: "/assets/img/logo.svg"
github_username: complexdatacollective
markdown: kramdown
toc:
  max_level: 3
  ordered_list: true
defaults:
  - scope:
      path: "_*" # an empty string here breaks the theme because it applies to the JS asset. use this instead
    values:
      layout: "page"
  - scope:
      path: "tutorials"
    values:
      toc: true
      layout: "tutorial"
  - scope:
      path: "docs/how-to"
    values:
      toc: true
      layout: "tutorial"
  - scope:
      path: "reference/key-concepts"
    values:
      layout: "key-concept"
  - scope:
      path: "reference/interface-documentation"
    values:
      layout: "interface-documentation"
remote_theme: pmarsceill/just-the-docs
color_scheme: network-canvas
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2016-2021 Complex Data Collective."

plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-toc
search_enabled: true
aux_links:
  Network Canvas Home:
  - "//networkcanvas.com"
permalink: pretty
# collections:
#   docs: # explanation
#     permalink: "/:path/"
#     output: true
#   tutorials: # tutorials
#     permalink: "/:collection/:path/"
#     output: true
#   technical-reference: #reference 
#     permalink: "/:collection/:path/"
#     output: true
#   how-to: #how-to
#     permalink: "/:collection/:path/"
#     output: true
ga_tracking: "UA-100029443-1"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
  - "vendor"
  - "README.md"
  - "ai files"
  - "scripts"
