---
title: Network Canvas Documentation
timezone: UTC
email: info@networkcanvas.com
description: Documentation and information about the Network Canvas project. Network Canvas is free suite of tools that facilitate cutting edge personal networks research.
logo: "/assets/img/logo.svg"
github_username: complexdatacollective
markdown: kramdown
toc:
  max_level: 3
  ordered_list: true
defaults:
  - scope:
      path: "docs"
    values:
      toc: true
      layout: "post"
remote_theme: pmarsceill/just-the-docs
color_scheme: network-canvas
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2016-2021 Complex Data Collective."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-toc
search_enabled: true
aux_links:
  Network Canvas Home:
  - "//networkcanvas.com"
permalink: pretty
ga_tracking: "UA-100029443-1"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
  - "vendor"
  - "README.md"
  - "ai files"
  - "scripts"
