---
title: Network Canvas Documentation
timezone: UTC
email: info@networkcanvas.com
description: Documentation and information about the Network Canvas project. Network Canvas is free suite of tools that facilitate cutting edge personal networks research.
logo: "/assets/img/logo.svg"
github_username: complexdatacollective
markdown: kramdown
toc:
  max_level: 3
  ordered_list: true
defaults:
  - scope:
      path: "docs"
    values:
      toc: true
      layout: "post"
remote_theme: pmarsceill/just-the-docs
color_scheme: network-canvas
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-toc
search_enabled: true
aux_links:
  Network Canvas Home:
  - "//networkcanvas.com"
permalink: pretty
ga_tracking: "UA-100029443-1"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
  - "vendor"
  - "README.md"
  - "ai files"
  - "scripts"
