# config.yml

backend:
  name: github
  repo: complexdatacollective/Documentation # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
media_folder: '/assets/uploads'
publish_mode: editorial_workflow
collections:
  - name: "page"
    label: "Page"
    folder: "/docs"
    media_folder: '/assets/uploads'
    create: true
    sortable_fields: ["title"]
    filter: { field: "has_parent", value: false }
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: false }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
      - { name: has_children, widget: "boolean", required: false }
      - { name: has_toc, widget: "boolean", required: false }
      - { name: nav_order, widget: "number", required: false }
      - { name: nav_exclude, widget: "boolean", required: false }
  - name: "interface-documentation"
    label: "Interface Documentation"
    folder: "/docs/interface-documentation"
    media_folder: '/assets/uploads'
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Interface Documentation" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
  - name: "key-concepts"
    label: "Key Concepts"
    folder: "/docs/key-concepts"
    media_folder: '/assets/uploads'
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Key Concepts" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
  - name: "research-design"
    label: "Research Design"
    folder: "/docs/research-design"
    media_folder: '/assets/uploads'
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Research Design" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
  - name: "technical-documentation"
    label: "Technical Documentation"
    folder: "/docs/technical-documentation"
    media_folder: '/assets/uploads'
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Technical Documentation" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
  - name: "tutorials"
    label: "Tutorials"
    folder: "/docs/tutorials"
    media_folder: '/assets/uploads'
    path: "/{{parent}}/{{title}}"
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Tutorials" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
