# config.yml

backend:
backend:
  name: git-gateway
local_backend: true
  # name: github
  # repo: complexdatacollective/Documentation # Path to your GitHub repository
  # branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: "docs"
    label: "Docs"
    folder: "docs"
    path: "{{parent}}/{{title}}"
    create: true
    sortable_fields: ["title", "parent"]
    view_groups:
      - label: 'Section'
        field: parent
    fields:
      - { name: title, label: Title }
      - name: parent
        widget: "relation"
        collection: "docs"
        search_fields: ["parent"]
        value_field: "parent"
        display_fields: ["parent"]
        required: false
      - { name: has_children, widget: "boolean", required: false }
      - { name: has_toc, widget: "boolean", required: false }
      - { name: nav_order, widget: "number", required: false }
      - { name: nav_exclude, widget: "boolean", required: false }
