# config.yml

backend:
  name: github
  repo: complexdatacollective/Documentation # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
media_folder: '/assets/uploads'
publish_mode: editorial_workflow
collections:
  - name: "page"
    label: "Page"
    folder: "/docs"
    create: true
    sortable_fields: ["title"]
    filter: { field: "has_parent", value: false }
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: false }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
      - { name: has_children, widget: "boolean", required: false }
      - { name: has_toc, widget: "boolean", required: false }
      - { name: nav_order, widget: "number", required: false }
      - { name: nav_exclude, widget: "boolean", required: false }
  - name: "interface-documentation"
    label: "Interface Documentation"
    folder: "/docs/interface-documentation"
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Parent", name: "parent", widget: "hidden", default: "Interface Documentation" }
      - { name: image, label: "Screenshot", widget: image }
      - { name: title, label: "Interface Name" }
      - { name: body, label: "Interface Summary", widget: markdown }
      - 
        name: good
        label: "Best Practices"
        widget: list
        allow_add: true
        summary: '{{fields.item}}'
        field: {label: "Item Text", name: item, widget: markdown, minimal: true, buttons: [bold, italic, code, link]}
      - 
        name: bad
        label: "Things to Avoid"
        widget: list
        allow_add: true
        summary: '{{fields.item}}'
        field: {label: "Item Text", name: item, widget: markdown, minimal: true, buttons: [bold, italic, code, link]}
  - name: "key-concepts"
    label: "Key Concepts"
    folder: "/docs/key-concepts"
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Key Concepts" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
  - name: "research-design"
    label: "Research Design"
    folder: "/docs/research-design"
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Research Design" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
  - name: "technical-documentation"
    label: "Technical Documentation"
    folder: "/docs/technical-documentation"
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Technical Documentation" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
  - name: "tutorial"
    label: "Tutorial"
    folder: "/docs/tutorials"
    create: true
    sortable_fields: ["title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Has parent", name: "has_parent", widget: "hidden", default: true }
      - { label: "Parent", name: "parent", widget: "hidden", default: "Tutorials" }
      - { name: title, label: Title }
      - { name: body, label: body, widget: markdown }
